- name: Add main promptline with git branch in it
  become: false
  tags: nvim
  blockinfile:
    dest: "~/.bashrc"
    block: |
      case "$TERM" in
        xterm-color|*-256color) PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ ';;
      esac
    create: yes
