---
# shoudl includ 2 vars,
# url - the url of the server e.g. cloud.example.com
# mail - the mail letsencrypt-companion is going to use (optional)

- hosts: localhost
  become: true
  roles:
    - role: nextcloud_server
      # url: cloud.example.com
      # mail: mymail@gmail.com

