---
- hosts: localhost
  become: true
  roles:
    - nvim_remove
    - role: nvim
      install_type: unstable
      # appimage: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
      # appimage_sha: sha256:https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage.sha256sum
      config_branch: main
