- name: get DEB arch
  shell: dpkg --print-architecture
  register: deb_arch

- name: Install npm dependencies
  tags: docker
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: latest
    update-cache: yes
     
- name: Add npm repo (with its apt-key) (armored keys should use .asc extension, binary should use .gpg)
  tags: docker
  block:
    - name: node | no apt key
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /etc/apt/keyrings/nodesource.asc

    - name: node | apt source for node 21.x
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ deb_arch.stdout }} signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_21.x nodistro main"
        state: present

- name: Install npm and nodejs
  tags: docker
  package:
    name:
      - nodejs
    state: latest
    update-cache: yes

