- name: Creating ~/ddns directory for the docker-compose file
  become: false
  file:
    path: '~/servers/ddns'
    state: directory

- name: Generate ddns docker-compose file
  become: false
  template:
    mode: 0700 #  only user can read/write/exec
    src: ddns_namecheap_docker_compose.j2
    dest: '~/servers/ddns/docker-compose.yml'
  vars:
    namecheap_pass: "{{ namecheap_pass }}"
    domain: "{{ domain }}"
    subdomain: "{{ subdomain }}"
    interval: "{{ interval }}" # optional
