- name: fzf | downloading from repo
  become: false
  tags: fzf, shell
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    clone: yes
    update: yes
    depth: 1
  register: fzf

- name: fzf | installing
  become: false
  tags: fzf, shell
  shell: ~/.fzf/install --all
  args:
    chdir: '~'
  when: fzf.changed
