- name: Remove "neovim" package
  become: true
  ansible.builtin.apt:
    name: neovim
    state: absent
    autoremove: yes

- name: Recursively remove '~/.local/share/nvim/'
  become: false
  ansible.builtin.file:
    path: ~/.local/share/nvim
    state: absent

- name: Recursively remove '~/.local/state/nvim/'
  become: false
  ansible.builtin.file:
    path: ~/.local/state/nvim
    state: absent

- name: Recursively remove '~/.cache/nvim/'
  become: false
  ansible.builtin.file:
    path: ~/.cache/nvim
    state: absent
