- name: Download nvim
  tags: nvim
  ansible.builtin.get_url:
    url: "{{appimage}}"
    dest: /usr/bin/nvim
    mode: 'a+x'
    checksum: "{{appimage_sha}}"

- name: Install nvim dependencies
  tags: nvim
  package:
    name:
      - ripgrep
      - gcc
      - libfuse2
    state: latest
    update-cache: yes

- name: Download nvim configuration from github
  become: false
  tags: nvim
  git:
    repo: https://github.com/ism-hub/nvim.git
    version: "{{config_branch}}"
    dest: ~/.config/nvim
    clone: yes
    update: yes
    depth: 1
