- name: get the user id running the deploy
  become: false
  local_action: command id -u
  register: user_id

- name: get the group id running the deploy
  become: false
  local_action: command id -g
  register: group_id

- name: Add dependent folders with the correct user (if not exists) - wireguard/config
  become: false
  ansible.builtin.file:
    path: ~/servers/wireguard/config
    state: directory

- name: Creating ~/servers/wireguard directory for the docker-compose file
  become: false
  file:
    path: '~/servers/wireguard'
    state: directory

- name: Generate docker-compose file
  become: false
  template:
    mode: 0700 #  only user can read/write/exec
    src: wireguard_docker_compose.j2
    dest: '~/servers/wireguard/docker-compose.yml'
  vars:
    uid: "{{ user_id.stdout }}"
    gid: "{{ group_id.stdout }}"
    vpn_url: "{{ vpn_url }}"
    peers: "{{ peers }}"
